"""Regenerate src/sim/assetManifest.ts from public/assets/microduck/."""
import os, json
base = 'public/assets/microduck'
xmls = sorted(f for f in os.listdir(base) if f.endswith('.xml'))
stls = sorted(os.listdir(os.path.join(base, 'assets')))
out = "// GENERATED by scripts/gen-manifest.py — do not edit by hand.\n"
out += "export const MODEL_XMLS = %s as const\n\n" % json.dumps(xmls, indent=2)
out += "export const MODEL_MESHES = %s as const\n" % json.dumps(stls, indent=2)
open('src/sim/assetManifest.ts','w').write(out)
print(f"{len(xmls)} xml, {len(stls)} meshes")
